name: Beta Test
on:
    push:
        branches:
            - main
jobs:
    beta-test:
        name: "Beta Test"
        uses: muselab-d2x/d2x/.github/workflows/beta-test{% if cookiecutter.project_type == "2GP Managed" %}-2gp{% elif cookiecutter.project_type == "2GP Unlocked" %}-unlocked{% endif %}.yml@main
        secrets:{% raw %}
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.{% if cookiecutter.dependencies %}CCI_{% endif %}GITHUB_TOKEN }}"{% endraw %}
            {% if cookiecutter.project_type == "1GP Managed" %}{% raw %}packaging-org-auth-url: "${{ secrets.PACKAGING_ORG_AUTH_URL }}"{% endraw %}{% endif %}
