name: >
  {% if cookiecutter.project_type != "Unpackaged" %}2GP {% endif %}Feature Test{% if cookiecutter.use_cumulusci_next %} and Snapshot{% endif %}
on:
    workflow_dispatch:
    push:
        branches:
            - feature/**
            - main
jobs:
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/feature-test{% if cookiecutter.project_type == "Unpackaged" %}{% elif cookiecutter.project_type == "2GP Unlocked" %}-unlocked{% else %}-2gp{% if cookiecutter.use_cumulusci_next %}-snapshot{% endif %}{% endif %}.yml@{% if cookiecutter.use_cumulusci_next %}cumulusci-next{% else %}main{% endif %}{% if cookiecutter.use_cumulusci_next %}
        with:
            create_pr_snapshot: true
            create_failure_snapshot: true
            environment_prefix: "Snapshot: "
            commit_status_context: Snapshot
        
        {% endif %}secrets:{% raw %}
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.{% endraw %}{% if cookiecutter.dependencies %}CCI_{% endif %}{% raw %}GITHUB_TOKEN }}"{% endraw %}
