name: {% if cookiecutter.project_type != "Unpackaged" %}2GP {% endif %}Feature Test
on:
    push:
        branches:
            - feature/**
            # Uncomment the line below to build commits on main
            # This is commented out by default to minimize scratch org usage
            #- main
jobs:
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/feature-test{% if cookiecutter.project_type != "Unpackaged" %}-2gp{% endif %}.yml@main
        secrets:{% raw %}
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"{% endraw %}